#!/bin/bash

start_container () {
    echo "Starting dev-term..."
    docker-compose run --rm term
}

stop_container () {
    echo "Stopping containers..."
    docker-compose down
}

run_up () {
    FLAG_HELP=false

    for a in ${BASH_ARGV[*]}; do
        if [ "$a" = "--help" ]; then
            FLAG_HELP=true
        fi
    done

    if [ "$FLAG_HELP" = true ]; then
        run_up_help
    else
        start_container
    fi
}

run_up_help () {
    echo ""
    echo "Usage:  jterm up"
    echo ""
    echo "Attaches to a terminal image - will start the image, if necessary."
}

run_down () {
    FLAG_FORCE=false
    FLAG_HELP=false

    for a in ${BASH_ARGV[*]}; do
        if [ "$a" = "--help" ]; then
            FLAG_HELP=true
        fi
    done
    
    if [ "$FLAG_HELP" = true ]; then
        run_down_help
    else
        stop_container
    fi
}

run_down_help () {
    echo ""
    echo "Usage:  jterm down [OPTIONS]"
    echo ""
    echo "Stops and discards any existing images."
}

run_help() {
    echo ""
    echo "Usage:  jterm COMMAND [OPTIONS]"
    echo ""
    echo "A command-line utility to help running the Docker-based terminal and utils."
    echo ""
    echo "Commands:"
    echo "  up         Starts and connects to the Docker-base terminal and any companion utilities."
    echo "  down       Shuts down and removes containerize applications."
    echo "  help       Prints usage information."
    echo ""
    echo "Run 'jterm COMMAND --help' for more information on a command."
}

if [ "$1" = "up" ]; then
    run_up
elif [ "$1" = "down" ]; then
    run_down
elif [ "$1" = "help" ]; then
    run_help
else
    run_help
fi
