KEYTIMEOUT=1

export EDITOR=vim
export PATH=/Users/jeff/google-cloud-sdk/bin:$HOME/.rbenv/shims:$HOME/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/sbin
#export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home

export GOROOT=/usr/local/go
export GOPATH=$HOME/Documents/code/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
alias pg.start='pg_ctl -D /usr/local/var/postgres start'
alias pg.stop='pg_ctl -D /usr/local/var/postgres stop'
alias ls='ls -G'
#source /Users/jeff/.iterm2_shell_integration.zsh
alias setup-ssh='eval `ssh-agent` && ssh-add && ssh-add ~/.ssh/google_compute_engine'
alias notes='cd ~/Dropbox/Notes/Notebooks'
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# prov-shit settings
export GOOGLE_SSH_USERNAME=ubuntu
export GOOGLE_SSH_KEY=$HOME/.ssh/google_compute_engine
export GOOGLE_CLIENT_EMAIL='jeff@foxcommerce.com'
export GOOGLE_JSON_KEY_LOCATION=$HOME/Documents/code/foxcommerce/highlander/prov-shit/foxcomm-staging.json
